services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  frontend:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"

  backend:
    build: ./backend
    environment:
      - DB_HOST=db
      - DB_NAME=product_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "3000:5000"
    depends_on:
      - db

  

volumes:
  db_data: